apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-control-plane
spec:
  podSelector: {matchLabels: {app: villani-control-plane}}
  policyTypes: [Ingress, Egress]
  ingress:
    - ports: [{protocol: TCP, port: 8000}]
  egress:
    - ports:
        - {protocol: TCP, port: 5432}
        - {protocol: UDP, port: 53}
