"""Closed-loop plugin contracts and safe execution boundaries."""

from .discovery import (
    PluginDiscoveryError,
    artifact_digest,
    discover_plugins,
    discover_plugins_from_configuration,
)
from .models import (
    AgentRunnerPlugin,
    ExecutionProviderPlugin,
    MaterializerPlugin,
    PluginCallRequest,
    PluginCallResponse,
    PluginExecutionError,
    PluginFailure,
    PluginKind,
    PluginManifest,
    ResourceRequirements,
    SelectorPlugin,
    VerifierPlugin,
)
from .transport import SubprocessPluginClient, decode_message, encode_message
from .rpc_adapters import (
    OutOfProcessAgentRunnerPlugin,
    OutOfProcessExecutionProviderPlugin,
    OutOfProcessMaterializerPlugin,
    OutOfProcessSelectorPlugin,
    OutOfProcessVerifierPlugin,
)
from .conformance import run_echo_conformance, validate_manifest_conformance
from .builtins import (
    AGENT_RUNNER_MANIFEST,
    EXECUTION_PROVIDER_MANIFEST,
    MATERIALIZER_MANIFEST,
    SELECTOR_MANIFEST,
    VERIFIER_MANIFEST,
    BuiltinAgentRunnerPlugin,
    BuiltinExecutionProviderPlugin,
    BuiltinMaterializerPlugin,
    BuiltinSelectorPlugin,
    BuiltinVerifierPlugin,
    builtin_plugin_manifests,
)

__all__ = [
    "AgentRunnerPlugin",
    "ExecutionProviderPlugin",
    "MaterializerPlugin",
    "PluginCallRequest",
    "PluginCallResponse",
    "PluginDiscoveryError",
    "PluginExecutionError",
    "PluginFailure",
    "PluginKind",
    "PluginManifest",
    "ResourceRequirements",
    "SelectorPlugin",
    "SubprocessPluginClient",
    "VerifierPlugin",
    "artifact_digest",
    "decode_message",
    "discover_plugins",
    "discover_plugins_from_configuration",
    "encode_message",
    "AGENT_RUNNER_MANIFEST",
    "EXECUTION_PROVIDER_MANIFEST",
    "MATERIALIZER_MANIFEST",
    "SELECTOR_MANIFEST",
    "VERIFIER_MANIFEST",
    "BuiltinAgentRunnerPlugin",
    "BuiltinExecutionProviderPlugin",
    "BuiltinMaterializerPlugin",
    "BuiltinSelectorPlugin",
    "BuiltinVerifierPlugin",
    "builtin_plugin_manifests",
    "run_echo_conformance",
    "validate_manifest_conformance",
    "OutOfProcessAgentRunnerPlugin",
    "OutOfProcessExecutionProviderPlugin",
    "OutOfProcessMaterializerPlugin",
    "OutOfProcessSelectorPlugin",
    "OutOfProcessVerifierPlugin",
]
