"""Canonical closed-loop protocol and deterministic controller."""

from .adapters import (
    EvidenceSelectorAdapter,
    PatchMaterializerAdapter,
    VillaniCodeAttemptAdapter,
    VillaniVerifierAdapter,
)
from .controller import ClosedLoopController
from .cli_classification import CliClassifierAdapter
from .cli_selection import CliSelectorAdapter
from .costs import CostBreakdown, actual_attempt_cost, estimate_attempt_cost
from .durable_io import append_jsonl_durable, read_jsonl_tolerant, write_json_atomic
from .interfaces import ClosedLoopRunRequest, ClosedLoopRunResult
from .failure_classification import FailureCategory, classify_failure
from .policy import BootstrapPolicyConfiguration, BootstrapPolicyEngine
from .verifier_routing import (
    VerifierCascade,
    VerifierPolicyEntry,
    VerifierRoute,
    VerifierRoutingContext,
    VerifierRoutingPolicy,
    required_capability,
    select_routes,
)
from .verification_evidence import (
    CandidateEligibility,
    FinalVerificationDecision,
    FocusedProbeReport,
    FocusedProbeRequest,
    FocusedProbeResult,
    RequirementEvidence,
    RepositoryValidationDecisionInput,
    SemanticReviewDecisionInput,
    VerificationEvidenceMatrix,
    compute_final_verification_decision,
)
from .protocol import (
    AttemptSnapshot,
    ClassificationSnapshot,
    EventEnvelope,
    MaterializationSnapshot,
    PolicyDecisionSnapshot,
    RunManifestSnapshot,
    RunStateSnapshot,
    SelectionSnapshot,
    StageUsage,
    TaskSnapshot,
    VerificationSnapshot,
)
from .protocol_v2 import (
    AgentCapabilityV2,
    ArtifactDescriptorV2,
    OutcomeV2,
    PolicyPublicationV2,
    ResourceV2,
    SpanV2,
    TelemetryEnvelopeV2,
    VerifierCapabilityV2,
)
from .translate_v2 import (
    legacy_event_id_to_span_id,
    legacy_trace_id_to_w3c,
    normalized_v2_jsonl,
    translate_v1_event,
    translate_v1_events,
    translate_v1_run,
)
from .schema_validation import (
    SCHEMA_V2_VERSION_TO_PATH,
    SCHEMA_VERSION_TO_PATH,
    ProtocolValidationError,
    ProtocolValidationIssue,
    collect_protocol_validation_issues,
    parse_protocol_document,
    validate_event_stream,
    validate_jsonl_event_stream,
    validate_protocol_document,
)
from .agent_systems.models import (
    AgentSystemIdentity,
    HarnessConformanceReport,
    HarnessDiscovery,
    HarnessResult,
)
from .agent_systems.registry import (
    AgentSystemRegistry,
    build_agent_system_registry,
    build_agent_system_runner,
)
from .agent_systems.configuration import (
    migrate_agent_system_configuration,
)
from .agent_systems.role_models import (
    AgentInvocationIdentity,
    AgentRole,
    AgentSystemCatalog,
    RoleBindings,
)
from .agent_systems.factories import (
    RoleFactoryDependencies,
    build_attempt_runner,
    build_classifier,
    build_selector,
    build_verifier,
)
from .qualification import (
    GateCReport,
    QualificationAssessment,
    QualificationInvalidation,
    QualificationObservation,
    QualificationPolicy,
    QualificationSnapshot,
    QualificationStore,
    QualificationTaskProfile,
    assess_qualification,
    build_gate_c_report,
    repository_qualification_context,
)

__all__ = [
    "AttemptSnapshot",
    "AgentSystemIdentity",
    "AgentInvocationIdentity",
    "AgentRole",
    "AgentSystemCatalog",
    "AgentSystemRegistry",
    "AgentCapabilityV2",
    "ArtifactDescriptorV2",
    "ClassificationSnapshot",
    "ClosedLoopController",
    "ClosedLoopRunRequest",
    "ClosedLoopRunResult",
    "BootstrapPolicyConfiguration",
    "BootstrapPolicyEngine",
    "CostBreakdown",
    "CandidateEligibility",
    "CliClassifierAdapter",
    "CliSelectorAdapter",
    "EventEnvelope",
    "EvidenceSelectorAdapter",
    "FailureCategory",
    "FinalVerificationDecision",
    "FocusedProbeReport",
    "FocusedProbeRequest",
    "FocusedProbeResult",
    "GateCReport",
    "HarnessConformanceReport",
    "HarnessDiscovery",
    "HarnessResult",
    "MaterializationSnapshot",
    "OutcomeV2",
    "PatchMaterializerAdapter",
    "PolicyDecisionSnapshot",
    "PolicyPublicationV2",
    "ProtocolValidationError",
    "ProtocolValidationIssue",
    "QualificationAssessment",
    "QualificationInvalidation",
    "QualificationObservation",
    "QualificationPolicy",
    "QualificationSnapshot",
    "QualificationStore",
    "QualificationTaskProfile",
    "RunManifestSnapshot",
    "RunStateSnapshot",
    "ResourceV2",
    "RequirementEvidence",
    "RoleBindings",
    "RoleFactoryDependencies",
    "RepositoryValidationDecisionInput",
    "SCHEMA_VERSION_TO_PATH",
    "SCHEMA_V2_VERSION_TO_PATH",
    "SelectionSnapshot",
    "SemanticReviewDecisionInput",
    "StageUsage",
    "SpanV2",
    "TaskSnapshot",
    "TelemetryEnvelopeV2",
    "VerificationSnapshot",
    "VerificationEvidenceMatrix",
    "VerifierCapabilityV2",
    "VillaniCodeAttemptAdapter",
    "VillaniVerifierAdapter",
    "VerifierCascade",
    "VerifierPolicyEntry",
    "VerifierRoute",
    "VerifierRoutingContext",
    "VerifierRoutingPolicy",
    "append_jsonl_durable",
    "assess_qualification",
    "build_agent_system_registry",
    "build_agent_system_runner",
    "build_attempt_runner",
    "build_classifier",
    "build_gate_c_report",
    "build_selector",
    "build_verifier",
    "actual_attempt_cost",
    "classify_failure",
    "compute_final_verification_decision",
    "collect_protocol_validation_issues",
    "estimate_attempt_cost",
    "parse_protocol_document",
    "legacy_event_id_to_span_id",
    "legacy_trace_id_to_w3c",
    "migrate_agent_system_configuration",
    "normalized_v2_jsonl",
    "read_jsonl_tolerant",
    "required_capability",
    "repository_qualification_context",
    "select_routes",
    "translate_v1_event",
    "translate_v1_events",
    "translate_v1_run",
    "validate_event_stream",
    "validate_jsonl_event_stream",
    "validate_protocol_document",
    "write_json_atomic",
]
