"""Canonical closed-loop protocol and deterministic controller."""

from .adapters import (
    EvidenceSelectorAdapter,
    PatchMaterializerAdapter,
    VillaniCodeAttemptAdapter,
    VillaniVerifierAdapter,
)
from .controller import ClosedLoopController
from .costs import CostBreakdown, actual_attempt_cost, estimate_attempt_cost
from .durable_io import append_jsonl_durable, read_jsonl_tolerant, write_json_atomic
from .interfaces import ClosedLoopRunRequest, ClosedLoopRunResult
from .failure_classification import FailureCategory, classify_failure
from .policy import BootstrapPolicyConfiguration, BootstrapPolicyEngine
from .protocol import (
    AttemptSnapshot,
    ClassificationSnapshot,
    EventEnvelope,
    MaterializationSnapshot,
    PolicyDecisionSnapshot,
    RunManifestSnapshot,
    RunStateSnapshot,
    SelectionSnapshot,
    StageUsage,
    TaskSnapshot,
    VerificationSnapshot,
)
from .protocol_v2 import (
    AgentCapabilityV2,
    ArtifactDescriptorV2,
    OutcomeV2,
    PolicyPublicationV2,
    ResourceV2,
    SpanV2,
    TelemetryEnvelopeV2,
    VerifierCapabilityV2,
)
from .translate_v2 import (
    legacy_event_id_to_span_id,
    legacy_trace_id_to_w3c,
    normalized_v2_jsonl,
    translate_v1_event,
    translate_v1_events,
    translate_v1_run,
)
from .schema_validation import (
    SCHEMA_V2_VERSION_TO_PATH,
    SCHEMA_VERSION_TO_PATH,
    ProtocolValidationError,
    ProtocolValidationIssue,
    collect_protocol_validation_issues,
    parse_protocol_document,
    validate_event_stream,
    validate_jsonl_event_stream,
    validate_protocol_document,
)

__all__ = [
    "AttemptSnapshot",
    "AgentCapabilityV2",
    "ArtifactDescriptorV2",
    "ClassificationSnapshot",
    "ClosedLoopController",
    "ClosedLoopRunRequest",
    "ClosedLoopRunResult",
    "BootstrapPolicyConfiguration",
    "BootstrapPolicyEngine",
    "CostBreakdown",
    "EventEnvelope",
    "EvidenceSelectorAdapter",
    "FailureCategory",
    "MaterializationSnapshot",
    "OutcomeV2",
    "PatchMaterializerAdapter",
    "PolicyDecisionSnapshot",
    "PolicyPublicationV2",
    "ProtocolValidationError",
    "ProtocolValidationIssue",
    "RunManifestSnapshot",
    "RunStateSnapshot",
    "ResourceV2",
    "SCHEMA_VERSION_TO_PATH",
    "SCHEMA_V2_VERSION_TO_PATH",
    "SelectionSnapshot",
    "StageUsage",
    "SpanV2",
    "TaskSnapshot",
    "TelemetryEnvelopeV2",
    "VerificationSnapshot",
    "VerifierCapabilityV2",
    "VillaniCodeAttemptAdapter",
    "VillaniVerifierAdapter",
    "append_jsonl_durable",
    "actual_attempt_cost",
    "classify_failure",
    "collect_protocol_validation_issues",
    "estimate_attempt_cost",
    "parse_protocol_document",
    "legacy_event_id_to_span_id",
    "legacy_trace_id_to_w3c",
    "normalized_v2_jsonl",
    "read_jsonl_tolerant",
    "translate_v1_event",
    "translate_v1_events",
    "translate_v1_run",
    "validate_event_stream",
    "validate_jsonl_event_stream",
    "validate_protocol_document",
    "write_json_atomic",
]
