"""record ingest protocol version

Revision ID: d4973fd72304
Revises: 4bf1fe1c3274
Create Date: 2026-07-11 17:25:29.030488
"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "d4973fd72304"
down_revision: Union[str, Sequence[str], None] = "4bf1fe1c3274"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ingest_batches",
        sa.Column("protocol_version", sa.String(length=32), server_default="v2", nullable=False),
    )
    op.add_column(
        "outcomes",
        sa.Column("attempt_key", sa.String(length=128), server_default="", nullable=False),
    )
    op.drop_constraint("uq_outcomes_attempt", "outcomes", type_="unique")
    op.create_unique_constraint(
        "uq_outcomes_attempt", "outcomes", ["organization_id", "run_id", "attempt_key"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ingest_batches", "protocol_version")
    # ### end Alembic commands ###
    op.drop_constraint("uq_outcomes_attempt", "outcomes", type_="unique")
    op.create_unique_constraint(
        "uq_outcomes_attempt", "outcomes", ["organization_id", "run_id", "attempt_id"]
    )
    op.drop_column("outcomes", "attempt_key")
